In [83]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("NSMES1988.csv")

In [84]:
# 1 Inspect the data and report the details from physical inspection – rows, columns, data ypes etc.

# Display the first 5 rows
df.head()
# Display the Last 5 rows
df.tail()

,Unnamed: 0,visits,nvisits,ovisits,novisits,emergency,hospital,health,chronic,adl,region,age,gender,married,school,income,employed,insurance,medicaid
4401,4402,11,0,0,0,0,0,average,0,normal,other,8.4,female,yes,8,2.249700,no,yes,no
4402,4403,12,0,0,0,0,0,average,2,normal,other,7.8,female,no,11,5.813200,no,yes,no
4403,4404,10,0,20,0,1,1,average,5,normal,other,7.3,male,yes,12,3.877916,no,yes,no
4404,4405,16,1,0,0,0,0,average,0,normal,other,6.6,female,yes,12,3.877916,no,yes,no
4405,4406,0,0,0,0,0,0,excellent,0,normal,other,7.1,male,yes,0,6.596800,yes,no,no

In [ ]:
# Check the dataset shape (rows and columns)
# df.shape
print("rows:",df.shape[0])
print("columns:",df.shape[1])
# List all column names
print("columns:",df.columns)

rows: 4406
columns: 19
columns: Index(['Unnamed: 0', 'visits', 'nvisits', 'ovisits', 'novisits', 'emergency',
       'hospital', 'health', 'chronic', 'adl', 'region', 'age', 'gender',
       'married', 'school', 'income', 'employed', 'insurance', 'medicaid'],
      dtype='str')

In [86]:
# Check data types and non-null values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4406 entries, 0 to 4405
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  4406 non-null   int64
 1   visits      4406 non-null   int64
 2   nvisits     4406 non-null   int64
 3   ovisits     4406 non-null   int64
 4   novisits    4406 non-null   int64
 5   emergency   4406 non-null   int64
 6   hospital    4406 non-null   int64
 7   health      4406 non-null   str
 8   chronic     4406 non-null   int64
 9   adl         4406 non-null   str
 10  region      4406 non-null   str
 11  age         4406 non-null   float64
 12  gender      4406 non-null   str
 13  married     4406 non-null   str
 14  school      4406 non-null   int64
 15  income      4406 non-null   float64
 16  employed    4406 non-null   str
 17  insurance   4406 non-null   str
 18  medicaid    4406 non-null   str
dtypes: float64(2), int64(9), str(8)
memory usage: 654.1 KB

In [87]:
# Check missing values
df.isnull().sum()

Unnamed: 0    0
visits        0
nvisits       0
ovisits       0
novisits      0
emergency     0
hospital      0
health        0
chronic       0
adl           0
region        0
age           0
gender        0
married       0
school        0
income        0
employed      0
insurance     0
medicaid      0
dtype: int64

In [88]:
# Check duplicate rows
df.duplicated().sum()

np.int64(0)

In [89]:
# Get summary statistics
df.describe()

,Unnamed: 0,visits,nvisits,ovisits,novisits,emergency,hospital,chronic,age,school,income
count,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000
mean,2203.500000,5.774399,1.618021,0.750794,0.536087,0.263504,0.295960,1.541988,7.402406,10.290286,2.527132
std,1272.046972,6.759225,5.317056,3.652759,3.879506,0.703659,0.746398,1.349632,0.633405,3.738736,2.924648
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.600000,0.000000,-1.012500
25%,1102.250000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.900000,8.000000,0.912150
50%,2203.500000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.300000,11.000000,1.698150
75%,3304.750000,8.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,7.800000,12.000000,3.172850
max,4406.000000,89.000000,104.000000,141.000000,155.000000,12.000000,8.000000,8.000000,10.900000,18.000000,54.835100

In [90]:
# For all columns (including text):
df.describe(include='all')

,Unnamed: 0,visits,nvisits,ovisits,novisits,emergency,hospital,health,chronic,adl,region,age,gender,married,school,income,employed,insurance,medicaid
count,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406.000000,4406,4406.000000,4406,4406,4406.000000,4406,4406,4406.000000,4406.000000,4406,4406,4406
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,2,4,NaN,2,2,NaN,NaN,2,2,2
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,average,NaN,normal,other,NaN,female,yes,NaN,NaN,no,yes,no
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3509,NaN,3507,1614,NaN,2628,2406,NaN,NaN,3951,3421,4004
mean,2203.500000,5.774399,1.618021,0.750794,0.536087,0.263504,0.295960,NaN,1.541988,NaN,NaN,7.402406,NaN,NaN,10.290286,2.527132,NaN,NaN,NaN
std,1272.046972,6.759225,5.317056,3.652759,3.879506,0.703659,0.746398,NaN,1.349632,NaN,NaN,0.633405,NaN,NaN,3.738736,2.924648,NaN,NaN,NaN
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,NaN,NaN,6.600000,NaN,NaN,0.000000,-1.012500,NaN,NaN,NaN
25%,1102.250000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,NaN,NaN,6.900000,NaN,NaN,8.000000,0.912150,NaN,NaN,NaN
50%,2203.500000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,NaN,NaN,7.300000,NaN,NaN,11.000000,1.698150,NaN,NaN,NaN
75%,3304.750000,8.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,2.000000,NaN,NaN,7.800000,NaN,NaN,12.000000,3.172850,NaN,NaN,NaN
max,4406.000000,89.000000,104.000000,141.000000,155.000000,12.000000,8.000000,NaN,8.000000,NaN,NaN,10.900000,NaN,NaN,18.000000,54.835100,NaN,NaN,NaN

In [91]:
# Check memory usage
df.memory_usage(deep=True)

Index            132
Unnamed: 0     35248
visits         35248
nvisits        35248
ovisits        35248
novisits       35248
emergency      35248
hospital       35248
health        245760
chronic        35248
adl           243229
region        242788
age            35248
gender        238774
married       227112
school         35248
income         35248
employed      225161
insurance     228127
medicaid      225108
dtype: int64

In [96]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 4406 entries, 0 to 4405
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  4406 non-null   int64
 1   visits      4406 non-null   int64
 2   nvisits     4406 non-null   int64
 3   ovisits     4406 non-null   int64
 4   novisits    4406 non-null   int64
 5   emergency   4406 non-null   int64
 6   hospital    4406 non-null   int64
 7   health      4406 non-null   str
 8   chronic     4406 non-null   int64
 9   adl         4406 non-null   str
 10  region      4406 non-null   str
 11  age         4406 non-null   float64
 12  gender      4406 non-null   str
 13  married     4406 non-null   str
 14  school      4406 non-null   int64
 15  income      4406 non-null   float64
 16  employed    4406 non-null   str
 17  insurance   4406 non-null   str
 18  medicaid    4406 non-null   str
dtypes: float64(2), int64(9), str(8)
memory usage: 2.2 MB

In [93]:
df.dtypes

Unnamed: 0      int64
visits          int64
nvisits         int64
ovisits         int64
novisits        int64
emergency       int64
hospital        int64
health            str
chronic         int64
adl               str
region            str
age           float64
gender            str
married           str
school          int64
income        float64
employed          str
insurance         str
medicaid          str
dtype: object

In [94]:
# Comment on the data types, their values and range, specifically on age and income columns.
df[['age','income']].describe()

               age       income
count  4406.000000  4406.000000
mean      7.402406     2.527132
std       0.633405     2.924648
min       6.600000    -1.012500
25%       6.900000     0.912150
50%       7.300000     1.698150
75%       7.800000     3.172850
max      10.900000    54.835100