# 0. Setup and Data Loading

In [92]:
# !pip install kagglehub

In [93]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [94]:
# take the data from the csv file and load it into a pandas dataframe
df1 = pd.read_csv('../Datasets/Lesson_04_Working_With_Pandas/Assisted_Practice_Dataset/Weather_data.csv')
df1.head()
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Day            30 non-null     int64
 1   Temperature    30 non-null     float64
 2   Precipitation  30 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 852.0 bytes

In [95]:
# load iris.xlsx file
df2 = pd.read_excel('../Datasets/Lesson_04_Working_With_Pandas/Dataset/Iris.xlsx')
df2.head()
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [96]:
# import kagglehub

# # Download latest version
# path = kagglehub.dataset_download("abhijitdahatonde/fifa-world-cup-all-dataset")

# print("Path to dataset files:", path)

In [97]:
# Copy the file to the current working directory but first create new folder named "fifa-world-cup-all-dataset" in the current working directory and then copy the files to that folder
# !mkdir -p "fifa-world-cup-all-dataset"
# !cp -r $path/* "fifa-world-cup-all-dataset/"

/Users/shubhamkeshari/.cache/kagglehub/datasets/abhijitdahatonde/fifa-world-cup-all-dataset/versions/1/international_matches1.csv

In [98]:
## Final data set 
df = pd.read_csv('../Datasets/Lesson_04_Working_With_Pandas/Assisted_Practice_Dataset/HousePrices.csv')
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [99]:
# shape of the data
df.shape

(4600, 18)

In [100]:
# check for all columes in the data
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='str')

In [101]:
df.dtypes

date                 str
price            float64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
street               str
city                 str
statezip             str
country              str
dtype: object

# Step 2: Data Inspection

In [102]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   str
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   str
 15  city           4600 non-null   str
 16  statezip       4600 non-null   str
 17  country        4600 non-null   str
dtypes: float64(4), int64(9), str(5)
memory usage: 647.0 KB

# Obsurvation

In [103]:
# numarical discriptive stats summary
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

In [104]:
# non numerical discriptive stats summary
df.describe(include='str')

                       date                 street     city  statezip country
count                  4600                   4600     4600      4600    4600
unique                   70                   4525       44        77       1
top     2014-06-23 00:00:00  2520 Mulberry Walk NE  Seattle  WA 98103     USA
freq                    142                      4     1573       148    4600

In [105]:
df.describe(exclude='number')

                       date                 street     city  statezip country
count                  4600                   4600     4600      4600    4600
unique                   70                   4525       44        77       1
top     2014-06-23 00:00:00  2520 Mulberry Walk NE  Seattle  WA 98103     USA
freq                    142                      4     1573       148    4600

In [106]:
df.describe(include='all')

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
count,4600,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600,4600,4600,4600
unique,70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4525,44,77,1
top,2014-06-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2520 Mulberry Walk NE,Seattle,WA 98103,USA
freq,142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1573,148,4600
mean,NaN,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261,NaN,NaN,NaN,NaN
std,NaN,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536,NaN,NaN,NaN,NaN
min,NaN,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000,NaN,NaN,NaN,NaN
50%,NaN,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000,NaN,NaN,NaN,NaN
75%,NaN,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000,NaN,NaN,NaN,NaN
max,NaN,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000,NaN,NaN,NaN,NaN

In [107]:
# null values 
df.isnull()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4596,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4597,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4598,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4599,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [108]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [109]:
# number all unique data in each column
df.nunique()

date               70
price            1741
bedrooms           10
bathrooms          26
sqft_living       566
sqft_lot         3113
floors              6
waterfront          2
view                5
condition           5
sqft_above        511
sqft_basement     207
yr_built          115
yr_renovated       60
street           4525
city               44
statezip           77
country             1
dtype: int64

In [110]:
# top 10 city count
df.city.value_counts()
df.city.value_counts().head(10)

city
Seattle        1573
Renton          293
Bellevue        286
Redmond         235
Kirkland        187
Issaquah        187
Kent            185
Auburn          176
Sammamish       175
Federal Way     148
Name: count, dtype: int64

### Obsurvations :
1. Data is haveing 18 colume and 4600 rows
2. Dataset cantains Date, Year columns witch need conversion to datetime
3. Waterfront, View, condition  seems to be catgorical in natuer
4. City data is concentrated for its 20% cityes, especially seattle

### Step 3 : Data Preprocessing

In [111]:
# Conversions
# Date column to datetime

df['date'] = pd.to_datetime(df['date'])

In [ ]:
# convert yr_built and yr_renovated to datetime (year)
df['yr_built'] = pd.to_datetime(df['yr_built'], format='%Y')
df['yr_renovated'] = df['yr_renovated']. replace(0, pd.NaT)
df['yr_renovated'] = pd.to_datetime(df['yr_renovated'], format="%Y")

In [113]:
# create categorical columns for waterfront
df['waterfront'] = df['waterfront'].astype('category')

In [114]:
# drop columns which are not required
# country, street
df.drop(['country', 'street'], axis=1, inplace=True)

In [115]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   datetime64[us]
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   category
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   1865 non-null   datetime64[us]
 14  city           4600 non-null   str
 15  statezip       4600 non-null   str
 16  lyr_built      4600 non-null   datetime64[us]
dtypes: category(1), datetime64[us](3), float64(4), int64(7), str(2)
memory usage: 579.6 KB

In [116]:
# mapping waterfront to 0:no, 1:yes
df['waterfront'] = df['waterfront'].map({0: 'No', 1: 'Yes'}) 
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city,statezip,lyr_built
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,No,0,3,1340,0,1955,2005-01-01,Shoreline,WA 98133,1955-01-01
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,No,4,5,3370,280,1921,NaT,Seattle,WA 98119,1921-01-01
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,No,0,4,1930,0,1966,NaT,Kent,WA 98042,1966-01-01
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,No,0,4,1000,1000,1963,NaT,Bellevue,WA 98008,1963-01-01
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,No,0,4,1140,800,1976,1992-01-01,Redmond,WA 98052,1976-01-01

In [117]:
# Create useful analytics columns
df.date.value_counts()

date
2014-06-23    142
2014-06-25    131
2014-06-26    131
2014-07-08    127
2014-07-09    121
             ...
2014-06-07      4
2014-07-06      3
2014-05-11      2
2014-07-04      2
2014-05-17      1
Name: count, Length: 70, dtype: int64

In [128]:
# create a age column for property listed

df['age'] = df.date.dt.year - df.yr_built.dt.year

df.head()

AttributeError: Can only use .dt accessor with datetimelike values

In [132]:
# if house is renovated or not
df['is_renovated'] = np.where(df.yr_renovated.isnull(), 'No', 'Yes')
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city,statezip,lyr_built,is_renovated
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,No,0,3,1340,0,1955,2005-01-01,Shoreline,WA 98133,1955-01-01,Yes
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,No,4,5,3370,280,1921,NaT,Seattle,WA 98119,1921-01-01,No
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,No,0,4,1930,0,1966,NaT,Kent,WA 98042,1966-01-01,No
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,No,0,4,1000,1000,1963,NaT,Bellevue,WA 98008,1963-01-01,No
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,No,0,4,1140,800,1976,1992-01-01,Redmond,WA 98052,1976-01-01,Yes

In [133]:
# total area = all sqft columns sum
df['total_area'] = df[['sqft_above', 'sqft_basement', 'sqft_living', 'sqft_lot']].sum(axis=1)
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city,statezip,lyr_built,is_renovated,total_area
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,No,0,3,1340,0,1955,2005-01-01,Shoreline,WA 98133,1955-01-01,Yes,10592
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,No,4,5,3370,280,1921,NaT,Seattle,WA 98119,1921-01-01,No,16350
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,No,0,4,1930,0,1966,NaT,Kent,WA 98042,1966-01-01,No,15807
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,No,0,4,1000,1000,1963,NaT,Bellevue,WA 98008,1963-01-01,No,12030
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,No,0,4,1140,800,1976,1992-01-01,Redmond,WA 98052,1976-01-01,Yes,14380

In [134]:
# new column for price categories
df['price_category'] = pd.qcut(df.price, 4, labels = ['Low', 'Medium', 'High', 'Very High'])
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city,statezip,lyr_built,is_renovated,total_area,price_category
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,No,0,3,1340,0,1955,2005-01-01,Shoreline,WA 98133,1955-01-01,Yes,10592,Low
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,No,4,5,3370,280,1921,NaT,Seattle,WA 98119,1921-01-01,No,16350,Very High
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,No,0,4,1930,0,1966,NaT,Kent,WA 98042,1966-01-01,No,15807,Medium
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,No,0,4,1000,1000,1963,NaT,Bellevue,WA 98008,1963-01-01,No,12030,Medium
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,No,0,4,1140,800,1976,1992-01-01,Redmond,WA 98052,1976-01-01,Yes,14380,High

In [ ]:
df['price_category'] = pd.cut(df.price, bins=[0, 200000, 500000, 1000000, 2000000, 5000000, float('inf')], 
                              labels=['0-200k', '200k-500k', '500k-1M', '1M-2M', '2M-5M', '5M+'])
pd.head()