# **Introduction to Pandas**

## __Agenda__

- Fundamentals of Pandas
  * Purpose of Pandas
  * Features of Pandas
- Data Structures
- Introduction to Series
  * Creating and Accessing Pandas Series Using Different Methods
  * Basic Information in Pandas Series
  * Operations and Transformations in Pandas Series
  * Querying a Series

## __1. Fundamentals of Pandas__

Pandas is an open-source library built on top of NumPy and is used for data manipulation.

- It introduces data structures like DataFrame and Series that make working with structured data more efficient.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_04_Working_with_Pandas/1_Introduction_to_Pandas/pandas.png)

### __1.1 Purpose of Pandas__
![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_04_Working_with_Pandas/1_Introduction_to_Pandas/Purpose_of_Pandas.png)

### __1.2 Features of Pandas__
![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Updated_Images/Lesson_4/4_01/Features_of_Pandas.png)

## __2. Data Structures__
The two main libraries of Pandas data structure are:
![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_04_Working_with_Pandas/1_Introduction_to_Pandas/Data_Structures.png)

## __3. Introduction to Series__
A Series is a one-dimensional array-like object containing data and labels or index.

It can be created with different data inputs:
![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Updated_Images/Lesson_4/4_01/Introduction_to_Series.png)

### __3.1 Creating and Accessing Pandas Series Using Different Methods:__

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
!pip install pandas==3.0.3

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 90.0 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.3 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.3 which is incompatible.
Successfully installed pandas-3.0.3

In [ ]:
import pandas as pd

# Creating a Pandas Series from a list
data = [1, 2, 3, 4, 5]
series = pd.Series(data)

# Creating a Pandas Series with a specified index
index = ['a', 'b', 'c', 'd', 'e']
series_with_index = pd.Series(data, index=index)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# show all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
list_items = [x for x in range(1,1001)]
series_1000 = pd.Series(list_items)
series_1000

0         1
1         2
2         3
3         4
4         5
5         6
6         7
7         8
8         9
9        10
10       11
11       12
12       13
13       14
14       15
15       16
16       17
17       18
18       19
19       20
20       21
21       22
22       23
23       24
24       25
25       26
26       27
27       28
28       29
29       30
30       31
31       32
32       33
33       34
34       35
35       36
36       37
37       38
38       39
39       40
40       41
41       42
42       43
43       44
44       45
45       46
46       47
47       48
48       49
49       50
50       51
51       52
52       53
53       54
54       55
55       56
56       57
57       58
58       59
59       60
60       61
61       62
62       63
63       64
64       65
65       66
66       67
67       68
68       69
69       70
70       71
71       72
72       73
73       74
74       75
75       76
76       77
77       78
78       79
79       80
80       81
81       82
82       83
83       84
84       85
85       86
86       87
87       88
88       89
89       90
90       91
91       92
92       93
93       94
94       95
95       96
96       97
97       98
98       99
99      100
100     101
101     102
102     103
103     104
104     105
105     106
106     107
107     108
108     109
109     110
110     111
111     112
112     113
113     114
114     115
115     116
116     117
117     118
118     119
119     120
120     121
121     122
122     123
123     124
124     125
125     126
126     127
127     128
128     129
129     130
130     131
131     132
132     133
133     134
134     135
135     136
136     137
137     138
138     139
139     140
140     141
141     142
142     143
143     144
144     145
145     146
146     147
147     148
148     149
149     150
150     151
151     152
152     153
153     154
154     155
155     156
156     157
157     158
158     159
159     160
160     161
161     162
162     163
163     164
164     165
165     166
166     167
167     168
168     169
169     170
170     171
171     172
172     173
173     174
174     175
175     176
176     177
177     178
178     179
179     180
180     181
181     182
182     183
183     184
184     185
185     186
186     187
187     188
188     189
189     190
190     191
191     192
192     193
193     194
194     195
195     196
196     197
197     198
198     199
199     200
200     201
201     202
202     203
203     204
204     205
205     206
206     207
207     208
208     209
209     210
210     211
211     212
212     213
213     214
214     215
215     216
216     217
217     218
218     219
219     220
220     221
221     222
222     223
223     224
224     225
225     226
226     227
227     228
228     229
229     230
230     231
231     232
232     233
233     234
234     235
235     236
236     237
237     238
238     239
239     240
240     241
241     242
242     243
243     244
244     245
245     246
246     247
247     248
248     249
249     250
250     251
251     252
252     253
253     254
254     255
255     256
256     257
257     258
258     259
259     260
260     261
261     262
262     263
263     264
264     265
265     266
266     267
267     268
268     269
269     270
270     271
271     272
272     273
273     274
274     275
275     276
276     277
277     278
278     279
279     280
280     281
281     282
282     283
283     284
284     285
285     286
286     287
287     288
288     289
289     290
290     291
291     292
292     293
293     294
294     295
295     296
296     297
297     298
298     299
299     300
300     301
301     302
302     303
303     304
304     305
305     306
306     307
307     308
308     309
309     310
310     311
311     312
312     313
313     314
314     315
315     316
316     317
317     318
318     319
319     320
320     321
321     322
322     323
323     324
324     325
325     326
326     327
327     328
328     329
329     330
330     331
331     332
332     333
333     334
334     335
335     336
336     337
337     338
338     339
339     340
340     341
341     342
342     343
343     344
344     345
345     346
346     347
347     348
348     349
349     350
350     351
351     352
352     353
353     354
354     355
355     356
356     357
357     358
358     359
359     360
360     361
361     362
362     363
363     364
364     365
365     366
366     367
367     368
368     369
369     370
370     371
371     372
372     373
373     374
374     375
375     376
376     377
377     378
378     379
379     380
380     381
381     382
382     383
383     384
384     385
385     386
386     387
387     388
388     389
389     390
390     391
391     392
392     393
393     394
394     395
395     396
396     397
397     398
398     399
399     400
400     401
401     402
402     403
403     404
404     405
405     406
406     407
407     408
408     409
409     410
410     411
411     412
412     413
413     414
414     415
415     416
416     417
417     418
418     419
419     420
420     421
421     422
422     423
423     424
424     425
425     426
426     427
427     428
428     429
429     430
430     431
431     432
432     433
433     434
434     435
435     436
436     437
437     438
438     439
439     440
440     441
441     442
442     443
443     444
444     445
445     446
446     447
447     448
448     449
449     450
450     451
451     452
452     453
453     454
454     455
455     456
456     457
457     458
458     459
459     460
460     461
461     462
462     463
463     464
464     465
465     466
466     467
467     468
468     469
469     470
470     471
471     472
472     473
473     474
474     475
475     476
476     477
477     478
478     479
479     480
480     481
481     482
482     483
483     484
484     485
485     486
486     487
487     488
488     489
489     490
490     491
491     492
492     493
493     494
494     495
495     496
496     497
497     498
498     499
499     500
500     501
501     502
502     503
503     504
504     505
505     506
506     507
507     508
508     509
509     510
510     511
511     512
512     513
513     514
514     515
515     516
516     517
517     518
518     519
519     520
520     521
521     522
522     523
523     524
524     525
525     526
526     527
527     528
528     529
529     530
530     531
531     532
532     533
533     534
534     535
535     536
536     537
537     538
538     539
539     540
540     541
541     542
542     543
543     544
544     545
545     546
546     547
547     548
548     549
549     550
550     551
551     552
552     553
553     554
554     555
555     556
556     557
557     558
558     559
559     560
560     561
561     562
562     563
563     564
564     565
565     566
566     567
567     568
568     569
569     570
570     571
571     572
572     573
573     574
574     575
575     576
576     577
577     578
578     579
579     580
580     581
581     582
582     583
583     584
584     585
585     586
586     587
587     588
588     589
589     590
590     591
591     592
592     593
593     594
594     595
595     596
596     597
597     598
598     599
599     600
600     601
601     602
602     603
603     604
604     605
605     606
606     607
607     608
608     609
609     610
610     611
611     612
612     613
613     614
614     615
615     616
616     617
617     618
618     619
619     620
620     621
621     622
622     623
623     624
624     625
625     626
626     627
627     628
628     629
629     630
630     631
631     632
632     633
633     634
634     635
635     636
636     637
637     638
638     639
639     640
640     641
641     642
642     643
643     644
644     645
645     646
646     647
647     648
648     649
649     650
650     651
651     652
652     653
653     654
654     655
655     656
656     657
657     658
658     659
659     660
660     661
661     662
662     663
663     664
664     665
665     666
666     667
667     668
668     669
669     670
670     671
671     672
672     673
673     674
674     675
675     676
676     677
677     678
678     679
679     680
680     681
681     682
682     683
683     684
684     685
685     686
686     687
687     688
688     689
689     690
690     691
691     692
692     693
693     694
694     695
695     696
696     697
697     698
698     699
699     700
700     701
701     702
702     703
703     704
704     705
705     706
706     707
707     708
708     709
709     710
710     711
711     712
712     713
713     714
714     715
715     716
716     717
717     718
718     719
719     720
720     721
721     722
722     723
723     724
724     725
725     726
726     727
727     728
728     729
729     730
730     731
731     732
732     733
733     734
734     735
735     736
736     737
737     738
738     739
739     740
740     741
741     742
742     743
743     744
744     745
745     746
746     747
747     748
748     749
749     750
750     751
751     752
752     753
753     754
754     755
755     756
756     757
757     758
758     759
759     760
760     761
761     762
762     763
763     764
764     765
765     766
766     767
767     768
768     769
769     770
770     771
771     772
772     773
773     774
774     775
775     776
776     777
777     778
778     779
779     780
780     781
781     782
782     783
783     784
784     785
785     786
786     787
787     788
788     789
789     790
790     791
791     792
792     793
793     794
794     795
795     796
796     797
797     798
798     799
799     800
800     801
801     802
802     803
803     804
804     805
805     806
806     807
807     808
808     809
809     810
810     811
811     812
812     813
813     814
814     815
815     816
816     817
817     818
818     819
819     820
820     821
821     822
822     823
823     824
824     825
825     826
826     827
827     828
828     829
829     830
830     831
831     832
832     833
833     834
834     835
835     836
836     837
837     838
838     839
839     840
840     841
841     842
842     843
843     844
844     845
845     846
846     847
847     848
848     849
849     850
850     851
851     852
852     853
853     854
854     855
855     856
856     857
857     858
858     859
859     860
860     861
861     862
862     863
863     864
864     865
865     866
866     867
867     868
868     869
869     870
870     871
871     872
872     873
873     874
874     875
875     876
876     877
877     878
878     879
879     880
880     881
881     882
882     883
883     884
884     885
885     886
886     887
887     888
888     889
889     890
890     891
891     892
892     893
893     894
894     895
895     896
896     897
897     898
898     899
899     900
900     901
901     902
902     903
903     904
904     905
905     906
906     907
907     908
908     909
909     910
910     911
911     912
912     913
913     914
914     915
915     916
916     917
917     918
918     919
919     920
920     921
921     922
922     923
923     924
924     925
925     926
926     927
927     928
928     929
929     930
930     931
931     932
932     933
933     934
934     935
935     936
936     937
937     938
938     939
939     940
940     941
941     942
942     943
943     944
944     945
945     946
946     947
947     948
948     949
949     950
950     951
951     952
952     953
953     954
954     955
955     956
956     957
957     958
958     959
959     960
960     961
961     962
962     963
963     964
964     965
965     966
966     967
967     968
968     969
969     970
970     971
971     972
972     973
973     974
974     975
975     976
976     977
977     978
978     979
979     980
980     981
981     982
982     983
983     984
984     985
985     986
986     987
987     988
988     989
989     990
990     991
991     992
992     993
993     994
994     995
995     996
996     997
997     998
998     999
999    1000
dtype: int64

### __3.2 Basic Information in Pandas Series__
These functions collectively help analysts summarize and understand the characteristics of the data, facilitating effective data exploration and analysis.

In [ ]:
# Return the first n rows
first_n_rows = series.head(3)

# Return the last n rows
last_n_rows = series.tail(3)

# Return dimensions (Rows, columns)
dimensions = series.shape

# Generate descriptive statistics
stats = series.describe()

# Return unique values
unique_values = series.unique()

# Return the number of unique values
num_unique_values = series.nunique()

### __3.3 Operations and Transformations in Pandas Series__
Operations and transformations in Pandas Series are crucial for modifying, enhancing, and cleaning data effectively.

They provide flexibility to adapt data to specific analyses or visualizations, preparing it for meaningful insights and ensuring data quality.

In [ ]:
# Element-wise addition
result_series = series + series_with_index

# Apply a function to each element
squared_series = series.apply(lambda x: x**2)

# Map values using a dictionary
mapped_series = series.map({1: 'one', 2: 'two', 3: 'three'})

# Sort the Series by values
sorted_series = series.sort_values()

# Check for missing values
missing_values = series.isnull()

# Fill missing values with a specified value
filled_series = series.fillna(0)

### __3.4 Querying a Series__
Selecting and filtering data based on specific conditions is an essential aspect of querying a Pandas Series.

The following examples illustrate common querying operations that can be applied to a Pandas Series:

In [ ]:
import pandas as pd

# Create a Pandas Series
data = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
series = pd.Series(data)

# Select elements greater than 30
selected_greater_than_30 = series[series > 30]

# Select elements equal to 20
selected_equal_to_20 = series[series == 20]

# Select elements not equal to 40
selected_not_equal_to_40 = series[series != 40]

# Select elements based on multiple conditions
selected_multiple_conditions = series[(series > 20) & (series < 50)]

# Select elements based on a list of values
selected_by_list = series[series.isin([20, 40, 60])]

# Select elements using string methods (if applicable)
string_series = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
selected_by_string_method = string_series[string_series.str.startswith('b')]

# Query based on index labels
selected_by_index_labels = series.loc[['a', 'c', 'e']]

# Query based on numeric position
selected_by_numeric_position = series.iloc[1:4]

# Display the results
print("Original Series:")
print(series)
print("\nSelected greater than 30:")
print(selected_greater_than_30)
print("\nSelected equal To 20:")
print(selected_equal_to_20)
print("\nSelected not equal to 40:")
print(selected_not_equal_to_40)
print("\nSelected based on multiple conditions:")
print(selected_multiple_conditions)
print("\nSelected based on list of values:")
print(selected_by_list)
print("\nSelected based on string method (startswith):")
print(selected_by_string_method)
print("\nSelected based on index labels:")
print(selected_by_index_labels)
print("\nSelected based on numeric position:")
print(selected_by_numeric_position)

Original Series:
a    10
b    20
c    30
d    40
e    50
dtype: int64

Selected greater than 30:
d    40
e    50
dtype: int64

Selected equal To 20:
b    20
dtype: int64

Selected not equal to 40:
a    10
b    20
c    30
e    50
dtype: int64

Selected based on multiple conditions:
c    30
d    40
dtype: int64

Selected based on list of values:
b    20
d    40
dtype: int64

Selected based on string method (startswith):
1    banana
dtype: object

Selected based on index labels:
a    10
c    30
e    50
dtype: int64

Selected based on numeric position:
b    20
c    30
d    40
dtype: int64

# __Assisted Practice__

## __Problem Statement:__
Use Pandas Series to analyze sales data for a retail store over a week and draw insights from the data.

### __Dataset:__
__Sample sales data__

sales_data = [120, 150, 130, 170, 160, 180, 140]

days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

## __Steps to Perform__

1. Create a Pandas Series for sales data
- Use a list of daily sales figures to create a Pandas Series
- Assign days of the week as the index
2. Access and manipulate sales data
- Access sales data for specific days using index labels
- Calculate total sales for the week
- Identify the day with the highest and lowest sales
   
3. Basic analysis of sales data
- Calculate the average sales for the week
- Determine the days with sales figures significantly different from the average

In [ ]:
df = pd.read_csv("/content/actors_sakila.csv")
df.head(10)

   actor_id first_name     last_name          last_update
0         1   PENELOPE       GUINESS  2006-02-15 04:34:33
1         2       NICK      WAHLBERG  2006-02-15 04:34:33
2         3         ED         CHASE  2006-02-15 04:34:33
3         4   JENNIFER         DAVIS  2006-02-15 04:34:33
4         5     JOHNNY  LOLLOBRIGIDA  2006-02-15 04:34:33
5         6      BETTE     NICHOLSON  2006-02-15 04:34:33
6         7      GRACE        MOSTEL  2006-02-15 04:34:33
7         8    MATTHEW     JOHANSSON  2006-02-15 04:34:33
8         9        JOE         SWANK  2006-02-15 04:34:33
9        10  CHRISTIAN         GABLE  2006-02-15 04:34:33

In [ ]:
# first top 10 rows
df.head(10)

   actor_id first_name     last_name          last_update
0         1   PENELOPE       GUINESS  2006-02-15 04:34:33
1         2       NICK      WAHLBERG  2006-02-15 04:34:33
2         3         ED         CHASE  2006-02-15 04:34:33
3         4   JENNIFER         DAVIS  2006-02-15 04:34:33
4         5     JOHNNY  LOLLOBRIGIDA  2006-02-15 04:34:33
5         6      BETTE     NICHOLSON  2006-02-15 04:34:33
6         7      GRACE        MOSTEL  2006-02-15 04:34:33
7         8    MATTHEW     JOHANSSON  2006-02-15 04:34:33
8         9        JOE         SWANK  2006-02-15 04:34:33
9        10  CHRISTIAN         GABLE  2006-02-15 04:34:33

In [ ]:
# bottom 8 rows
df.tail(8)

     actor_id first_name    last_name          last_update
192       193       BURT       TEMPLE  2006-02-15 04:34:33
193       194      MERYL        ALLEN  2006-02-15 04:34:33
194       195      JAYNE  SILVERSTONE  2006-02-15 04:34:33
195       196       BELA       WALKEN  2006-02-15 04:34:33
196       197      REESE         WEST  2006-02-15 04:34:33
197       198       MARY       KEITEL  2006-02-15 04:34:33
198       199      JULIA      FAWCETT  2006-02-15 04:34:33
199       200      THORA       TEMPLE  2006-02-15 04:34:33

In [ ]:
# random 3 rows
df.sample(3)

     actor_id first_name last_name          last_update
105       106    GROUCHO     DUNST  2006-02-15 04:34:33
177       178       LISA    MONROE  2006-02-15 04:34:33
152       153     MINNIE    KILMER  2006-02-15 04:34:33

In [ ]:
# complete information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   actor_id     200 non-null    int64
 1   first_name   200 non-null    str
 2   last_name    200 non-null    str
 3   last_update  200 non-null    str
dtypes: int64(1), str(3)
memory usage: 12.3 KB

In [ ]:
# shape of the dataframe
df.shape

(200, 4)

In [ ]:
# descriptive stats - numerical
df.describe()

         actor_id
count  200.000000
mean   100.500000
std     57.879185
min      1.000000
25%     50.750000
50%    100.500000
75%    150.250000
max    200.000000

In [ ]:
# descriptive atsts of categorical/text columns
df.describe(include = 'str')

       first_name last_name          last_update
count         200       200                  200
unique        128       121                    1
top      PENELOPE    KILMER  2006-02-15 04:34:33
freq            4         5                  200

In [ ]:
# show all
df.describe(include = 'all')

          actor_id first_name last_name          last_update
count   200.000000        200       200                  200
unique         NaN        128       121                    1
top            NaN   PENELOPE    KILMER  2006-02-15 04:34:33
freq           NaN          4         5                  200
mean    100.500000        NaN       NaN                  NaN
std      57.879185        NaN       NaN                  NaN
min       1.000000        NaN       NaN                  NaN
25%      50.750000        NaN       NaN                  NaN
50%     100.500000        NaN       NaN                  NaN
75%     150.250000        NaN       NaN                  NaN
max     200.000000        NaN       NaN                  NaN

In [ ]:
# null values
df.isnull().sum()

actor_id       0
first_name     0
last_name      0
last_update    0
dtype: int64

In [ ]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 100.4 KB

In [ ]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
# Percent of null values
df.isna().sum() / len(df) * 100

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

In [ ]:
# Null values - Fill it (Data Imputation) or simply Drop the column (>40%)
# Let us fill Embark_town
df.embark_town.value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [ ]:
# filling the embark column with mode value
df.embark_town.fillna('Southampton', inplace = True)

/tmp/ipykernel_1181/1660462596.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.embark_town.fillna('Southampton', inplace = True)

0      Southampton
1        Cherbourg
2      Southampton
3      Southampton
4      Southampton
5       Queenstown
6      Southampton
7      Southampton
8      Southampton
9        Cherbourg
10     Southampton
11     Southampton
12     Southampton
13     Southampton
14     Southampton
15     Southampton
16      Queenstown
17     Southampton
18     Southampton
19       Cherbourg
20     Southampton
21     Southampton
22      Queenstown
23     Southampton
24     Southampton
25     Southampton
26       Cherbourg
27     Southampton
28      Queenstown
29     Southampton
30       Cherbourg
31       Cherbourg
32      Queenstown
33     Southampton
34       Cherbourg
35     Southampton
36       Cherbourg
37     Southampton
38     Southampton
39       Cherbourg
40     Southampton
41     Southampton
42       Cherbourg
43       Cherbourg
44      Queenstown
45     Southampton
46      Queenstown
47      Queenstown
48       Cherbourg
49     Southampton
50     Southampton
51     Southampton
52       Cherbourg
53     Southampton
54       Cherbourg
55     Southampton
56     Southampton
57       Cherbourg
58     Southampton
59     Southampton
60       Cherbourg
61     Southampton
62     Southampton
63     Southampton
64       Cherbourg
65       Cherbourg
66     Southampton
67     Southampton
68     Southampton
69     Southampton
70     Southampton
71     Southampton
72     Southampton
73       Cherbourg
74     Southampton
75     Southampton
76     Southampton
77     Southampton
78     Southampton
79     Southampton
80     Southampton
81     Southampton
82      Queenstown
83     Southampton
84     Southampton
85     Southampton
86     Southampton
87     Southampton
88     Southampton
89     Southampton
90     Southampton
91     Southampton
92     Southampton
93     Southampton
94     Southampton
95     Southampton
96       Cherbourg
97       Cherbourg
98     Southampton
99     Southampton
100    Southampton
101    Southampton
102    Southampton
103    Southampton
104    Southampton
105    Southampton
106    Southampton
107    Southampton
108    Southampton
109     Queenstown
110    Southampton
111      Cherbourg
112    Southampton
113    Southampton
114      Cherbourg
115    Southampton
116     Queenstown
117    Southampton
118      Cherbourg
119    Southampton
120    Southampton
121    Southampton
122      Cherbourg
123    Southampton
124    Southampton
125      Cherbourg
126     Queenstown
127    Southampton
128      Cherbourg
129    Southampton
130      Cherbourg
131    Southampton
132    Southampton
133    Southampton
134    Southampton
135      Cherbourg
136    Southampton
137    Southampton
138    Southampton
139      Cherbourg
140      Cherbourg
141    Southampton
142    Southampton
143     Queenstown
144    Southampton
145    Southampton
146    Southampton
147    Southampton
148    Southampton
149    Southampton
150    Southampton
151    Southampton
152    Southampton
153    Southampton
154    Southampton
155      Cherbourg
156     Queenstown
157    Southampton
158    Southampton
159    Southampton
160    Southampton
161    Southampton
162    Southampton
163    Southampton
164    Southampton
165    Southampton
166    Southampton
167    Southampton
168    Southampton
169    Southampton
170    Southampton
171     Queenstown
172    Southampton
173    Southampton
174      Cherbourg
175    Southampton
176    Southampton
177      Cherbourg
178    Southampton
179    Southampton
180    Southampton
181      Cherbourg
182    Southampton
183    Southampton
184    Southampton
185    Southampton
186     Queenstown
187    Southampton
188     Queenstown
189    Southampton
190    Southampton
191    Southampton
192    Southampton
193    Southampton
194      Cherbourg
195      Cherbourg
196     Queenstown
197    Southampton
198     Queenstown
199    Southampton
200    Southampton
201    Southampton
202    Southampton
203      Cherbourg
204    Southampton
205    Southampton
206    Southampton
207      Cherbourg
208     Queenstown
209      Cherbourg
210    Southampton
211    Southampton
212    Southampton
213    Southampton
214     Queenstown
215      Cherbourg
216    Southampton
217    Southampton
218      Cherbourg
219    Southampton
220    Southampton
221    Southampton
222    Southampton
223    Southampton
224    Southampton
225    Southampton
226    Southampton
227    Southampton
228    Southampton
229    Southampton
230    Southampton
231    Southampton
232    Southampton
233    Southampton
234    Southampton
235    Southampton
236    Southampton
237    Southampton
238    Southampton
239    Southampton
240      Cherbourg
241     Queenstown
242    Southampton
243    Southampton
244      Cherbourg
245     Queenstown
246    Southampton
247    Southampton
248    Southampton
249    Southampton
250    Southampton
251    Southampton
252    Southampton
253    Southampton
254    Southampton
255      Cherbourg
256      Cherbourg
257    Southampton
258      Cherbourg
259    Southampton
260     Queenstown
261    Southampton
262    Southampton
263    Southampton
264     Queenstown
265    Southampton
266    Southampton
267    Southampton
268    Southampton
269    Southampton
270    Southampton
271    Southampton
272    Southampton
273      Cherbourg
274     Queenstown
275    Southampton
276    Southampton
277    Southampton
278     Queenstown
279    Southampton
280     Queenstown
281    Southampton
282    Southampton
283    Southampton
284    Southampton
285      Cherbourg
286    Southampton
287    Southampton
288    Southampton
289     Queenstown
290    Southampton
291      Cherbourg
292      Cherbourg
293    Southampton
294    Southampton
295      Cherbourg
296      Cherbourg
297    Southampton
298    Southampton
299      Cherbourg
300     Queenstown
301     Queenstown
302    Southampton
303     Queenstown
304    Southampton
305    Southampton
306      Cherbourg
307      Cherbourg
308      Cherbourg
309      Cherbourg
310      Cherbourg
311      Cherbourg
312    Southampton
313    Southampton
314    Southampton
315    Southampton
316    Southampton
317    Southampton
318    Southampton
319      Cherbourg
320    Southampton
321    Southampton
322     Queenstown
323    Southampton
324    Southampton
325      Cherbourg
326    Southampton
327    Southampton
328    Southampton
329      Cherbourg
330     Queenstown
331    Southampton
332    Southampton
333    Southampton
334    Southampton
335    Southampton
336    Southampton
337      Cherbourg
338    Southampton
339    Southampton
340    Southampton
341    Southampton
342    Southampton
343    Southampton
344    Southampton
345    Southampton
346    Southampton
347    Southampton
348    Southampton
349    Southampton
350    Southampton
351    Southampton
352      Cherbourg
353    Southampton
354      Cherbourg
355    Southampton
356    Southampton
357    Southampton
358     Queenstown
359     Queenstown
360    Southampton
361      Cherbourg
362      Cherbourg
363    Southampton
364     Queenstown
365    Southampton
366      Cherbourg
367      Cherbourg
368     Queenstown
369      Cherbourg
370      Cherbourg
371    Southampton
372    Southampton
373      Cherbourg
374    Southampton
375      Cherbourg
376    Southampton
377      Cherbourg
378      Cherbourg
379    Southampton
380      Cherbourg
381      Cherbourg
382    Southampton
383    Southampton
384    Southampton
385    Southampton
386    Southampton
387    Southampton
388     Queenstown
389      Cherbourg
390    Southampton
391    Southampton
392    Southampton
393      Cherbourg
394    Southampton
395    Southampton
396    Southampton
397    Southampton
398    Southampton
399    Southampton
400    Southampton
401    Southampton
402    Southampton
403    Southampton
404    Southampton
405    Southampton
406    Southampton
407    Southampton
408    Southampton
409    Southampton
410    Southampton
411     Queenstown
412     Queenstown
413    Southampton
414    Southampton
415    Southampton
416    Southampton
417    Southampton
418    Southampton
419    Southampton
420      Cherbourg
421     Queenstown
422    Southampton
423    Southampton
424    Southampton
425    Southampton
426    Southampton
427    Southampton
428     Queenstown
429    Southampton
430    Southampton
431    Southampton
432    Southampton
433    Southampton
434    Southampton
435    Southampton
436    Southampton
437    Southampton
438    Southampton
439    Southampton
440    Southampton
441    Southampton
442    Southampton
443    Southampton
444    Southampton
445    Southampton
446    Southampton
447    Southampton
448      Cherbourg
449    Southampton
450    Southampton
451    Southampton
452      Cherbourg
453      Cherbourg
454    Southampton
455      Cherbourg
456    Southampton
457    Southampton
458    Southampton
459     Queenstown
460    Southampton
461    Southampton
462    Southampton
463    Southampton
464    Southampton
465    Southampton
466    Southampton
467    Southampton
468     Queenstown
469      Cherbourg
470    Southampton
471    Southampton
472    Southampton
473      Cherbourg
474    Southampton
475    Southampton
476    Southampton
477    Southampton
478    Southampton
479    Southampton
480    Southampton
481    Southampton
482    Southampton
483    Southampton
484      Cherbourg
485    Southampton
486    Southampton
487      Cherbourg
488    Southampton
489    Southampton
490    Southampton
491    Southampton
492    Southampton
493      Cherbourg
494    Southampton
495      Cherbourg
496      Cherbourg
497    Southampton
498    Southampton
499    Southampton
500    Southampton
501     Queenstown
502     Queenstown
503    Southampton
504    Southampton
505      Cherbourg
506    Southampton
507    Southampton
508    Southampton
509    Southampton
510     Queenstown
511    Southampton
512    Southampton
513      Cherbourg
514    Southampton
515    Southampton
516    Southampton
517     Queenstown
518    Southampton
519    Southampton
520    Southampton
521    Southampton
522      Cherbourg
523      Cherbourg
524      Cherbourg
525     Queenstown
526    Southampton
527    Southampton
528    Southampton
529    Southampton
530    Southampton
531      Cherbourg
532      Cherbourg
533      Cherbourg
534    Southampton
535    Southampton
536    Southampton
537      Cherbourg
538    Southampton
539      Cherbourg
540    Southampton
541    Southampton
542    Southampton
543    Southampton
544      Cherbourg
545    Southampton
546    Southampton
547      Cherbourg
548    Southampton
549    Southampton
550      Cherbourg
551    Southampton
552     Queenstown
553      Cherbourg
554    Southampton
555    Southampton
556      Cherbourg
557      Cherbourg
558    Southampton
559    Southampton
560     Queenstown
561    Southampton
562    Southampton
563    Southampton
564    Southampton
565    Southampton
566    Southampton
567    Southampton
568      Cherbourg
569    Southampton
570    Southampton
571    Southampton
572    Southampton
573     Queenstown
574    Southampton
575    Southampton
576    Southampton
577    Southampton
578      Cherbourg
579    Southampton
580    Southampton
581      Cherbourg
582    Southampton
583      Cherbourg
584      Cherbourg
585    Southampton
586    Southampton
587      Cherbourg
588    Southampton
589    Southampton
590    Southampton
591      Cherbourg
592    Southampton
593     Queenstown
594    Southampton
595    Southampton
596    Southampton
597    Southampton
598      Cherbourg
599      Cherbourg
600    Southampton
601    Southampton
602    Southampton
603    Southampton
604      Cherbourg
605    Southampton
606    Southampton
607    Southampton
608      Cherbourg
609    Southampton
610    Southampton
611    Southampton
612     Queenstown
613     Queenstown
614    Southampton
615    Southampton
616    Southampton
617    Southampton
618    Southampton
619    Southampton
620      Cherbourg
621    Southampton
622      Cherbourg
623    Southampton
624    Southampton
625    Southampton
626     Queenstown
627    Southampton
628    Southampton
629     Queenstown
630    Southampton
631    Southampton
632      Cherbourg
633    Southampton
634    Southampton
635    Southampton
636    Southampton
637    Southampton
638    Southampton
639    Southampton
640    Southampton
641      Cherbourg
642    Southampton
643    Southampton
644      Cherbourg
645      Cherbourg
646    Southampton
647      Cherbourg
648    Southampton
649    Southampton
650    Southampton
651    Southampton
652    Southampton
653     Queenstown
654     Queenstown
655    Southampton
656    Southampton
657     Queenstown
658    Southampton
659      Cherbourg
660    Southampton
661      Cherbourg
662    Southampton
663    Southampton
664    Southampton
665    Southampton
666    Southampton
667    Southampton
668    Southampton
669    Southampton
670    Southampton
671    Southampton
672    Southampton
673    Southampton
674    Southampton
675    Southampton
676    Southampton
677    Southampton
678    Southampton
679      Cherbourg
680     Queenstown
681      Cherbourg
682    Southampton
683    Southampton
684    Southampton
685      Cherbourg
686    Southampton
687    Southampton
688    Southampton
689    Southampton
690    Southampton
691      Cherbourg
692    Southampton
693      Cherbourg
694    Southampton
695    Southampton
696    Southampton
697     Queenstown
698      Cherbourg
699    Southampton
700      Cherbourg
701    Southampton
702      Cherbourg
703     Queenstown
704    Southampton
705    Southampton
706    Southampton
707    Southampton
708    Southampton
709      Cherbourg
710      Cherbourg
711    Southampton
712    Southampton
713    Southampton
714    Southampton
715    Southampton
716      Cherbourg
717    Southampton
718     Queenstown
719    Southampton
720    Southampton
721    Southampton
722    Southampton
723    Southampton
724    Southampton
725    Southampton
726    Southampton
727     Queenstown
728    Southampton
729    Southampton
730    Southampton
731      Cherbourg
732    Southampton
733    Southampton
734    Southampton
735    Southampton
736    Southampton
737      Cherbourg
738    Southampton
739    Southampton
740    Southampton
741    Southampton
742      Cherbourg
743    Southampton
744    Southampton
745    Southampton
746    Southampton
747    Southampton
748    Southampton
749     Queenstown
750    Southampton
751    Southampton
752    Southampton
753    Southampton
754    Southampton
755    Southampton
756    Southampton
757    Southampton
758    Southampton
759    Southampton
760    Southampton
761    Southampton
762      Cherbourg
763    Southampton
764    Southampton
765    Southampton
766      Cherbourg
767     Queenstown
768     Queenstown
769    Southampton
770    Southampton
771    Southampton
772    Southampton
773      Cherbourg
774    Southampton
775    Southampton
776     Queenstown
777    Southampton
778     Queenstown
779    Southampton
780      Cherbourg
781    Southampton
782    Southampton
783    Southampton
784    Southampton
785    Southampton
786    Southampton
787     Queenstown
788    Southampton
789      Cherbourg
790     Queenstown
791    Southampton
792    Southampton
793      Cherbourg
794    Southampton
795    Southampton
796    Southampton
797    Southampton
798      Cherbourg
799    Southampton
800    Southampton
801    Southampton
802    Southampton
803      Cherbourg
804    Southampton
805    Southampton
806    Southampton
807    Southampton
808    Southampton
809    Southampton
810    Southampton
811    Southampton
812    Southampton
813    Southampton
814    Southampton
815    Southampton
816    Southampton
817      Cherbourg
818    Southampton
819    Southampton
820    Southampton
821    Southampton
822    Southampton
823    Southampton
824    Southampton
825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829    Southampton
830      Cherbourg
831    Southampton
832      Cherbourg
833    Southampton
834    Southampton
835      Cherbourg
836    Southampton
837    Southampton
838    Southampton
839      Cherbourg
840    Southampton
841    Southampton
842      Cherbourg
843      Cherbourg
844    Southampton
845    Southampton
846    Southampton
847      Cherbourg
848    Southampton
849      Cherbourg
850    Southampton
851    Southampton
852      Cherbourg
853    Southampton
854    Southampton
855    Southampton
856    Southampton
857    Southampton
858      Cherbourg
859      Cherbourg
860    Southampton
861    Southampton
862    Southampton
863    Southampton
864    Southampton
865    Southampton
866      Cherbourg
867    Southampton
868    Southampton
869    Southampton
870    Southampton
871    Southampton
872    Southampton
873    Southampton
874      Cherbourg
875      Cherbourg
876    Southampton
877    Southampton
878    Southampton
879      Cherbourg
880    Southampton
881    Southampton
882    Southampton
883    Southampton
884    Southampton
885     Queenstown
886    Southampton
887    Southampton
888    Southampton
889      Cherbourg
890     Queenstown
Name: embark_town, dtype: str

In [ ]:
# Deck column - Remove this column from our dataset - Drop
df.drop('deck', axis = 1, inplace = True)